# -*- coding: utf-8 -*-
"""Tugas AED - 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ou98leOCzIOTFDJ0cdyIeyRkfCSicbJv

# Tugas Analisis Eksplorasi Data - Pertemuan 8
**Haidar Ramdhani - G1401221005**

## A. Read Data
Data yang digunakan adalah data Indeks Pembangunan Manusia (IPM), Pengeluaran per Kapita (PK), dan Rata-rata Lama Sekolah (RLS) berdasarkan gender dari 27 kabupaten/kota di Provinsi Jawa Barat pada tahun 2022. Data diperoleh dari situs [Open Data Jabar](https://opendata.jabarprov.go.id).
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

data = pd.read_excel("/content/drive/My Drive/Colab Notebooks/IPM PK.xlsx")
data

"""## B. Eksplorasi dengan Plot
### 1) *Scatter Plot* Rata-rata Lama Sekolah dan Pengeluaran per Kapita


"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

sns.set()
plt.figure(figsize=(12,4.5))
sns.scatterplot(x='RLS', y='PK', data=data)

plt.suptitle('Scatter Plot RLS dan PK')

plt.show()

"""*Scatter plot* tersebut menunjukkan bagaimana sebaran data dan hubungan antara variabel RLS dengan PK. Terlihat bahwa *trend* dari hubungan kedua peubah ini berupa linear positif. Dapat dilihat bahwa nilai minimum dari RLS terletak di sekitar angka 6.1 sementara nilai maksimumnya terletak di sekitar angka 12.1. Sementara itu, nilai minimum dari data PK terletak di bawah angka 5000, sementara nilai maksimumnya di atas angka 22500.

### 2) *Scatter Plot* - Histogram Rata-rata Lama Sekolah dan Pengeluaran per Kapita
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.gridspec import GridSpec

sns.set()

# Membuat figure dan grid
fig = plt.figure(figsize = (10,7))
gs = GridSpec(4, 4, hspace=0.2)

# Menambah subplot
ax_scatter = fig.add_subplot(gs[1:4, 0:3])
ax_hist_y = fig.add_subplot(gs[0, 0:3])
ax_hist_x = fig.add_subplot(gs[1:4, 3])

# Scatter plot
sns.scatterplot(x='RLS', y='PK', data=data,  ax=ax_scatter)

ax_hist_x.set_xticklabels([])
ax_hist_x.set_yticklabels([])
ax_hist_y.set_xticklabels([])
ax_hist_y.set_yticklabels([])

plt.suptitle('Scatter Plot - Histogram RLS dan PK')

# Histogram
ax_hist_x.hist(data['RLS'], orientation='horizontal')
ax_hist_y.hist(data['PK'], orientation='vertical')

plt.show()

"""Grafik di atas adalah *scatter plot* yang terintegrasi dengan histogram untuk tiap peubah. Seperti informasi yang diperoleh sebelumnya antara peubah RLS dan PK, sekarang dapat terlihat lebih jelas bagaimana sebaran tiap peubah melalui histogram.

Histogram RLS memperlihatkan lebih jelas bahwa data RLS cenderung terpusat pada interval 9 - 10. Sementara itu, histogram PK memperlihatkan lebih jelas bahwa data PK cenderung tersebar rata, tetapi sedikit lebih terpusat pada interval 6000 - 11000.

Pada histogram tiap peubah tidak terlihat pencilan, tetapi ketika dihubungkan keduanya dalam *scatter plot*, terlihat adanya tiga titik data yang letaknya cukup jauh dari pusat sebaran sehingga berpotensi menjadi pencilan.

### 3) *Scatter Plot* - Histogram Rata-rata Lama Sekolah dan Pengeluaran per Kapita berdasarkan Gender (Sebaran)
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.gridspec import GridSpec

sns.set()

# Membuat figure dan grid
fig = plt.figure(figsize=(10, 7))
gs = GridSpec(4, 4, hspace=0.2)

# Menambah subplot
ax_scatter = fig.add_subplot(gs[1:4, 0:3])
ax_hist_y = fig.add_subplot(gs[0, 0:3])
ax_hist_x = fig.add_subplot(gs[1:4, 3])

# Scatter plot
sns.scatterplot(x='RLS', y='PK', data=data, hue='Gender', ax=ax_scatter)

# Histogram per kategori
colors = sns.color_palette()
for i, (gender, color) in enumerate(zip(data['Gender'].unique(), colors)):
    ax_hist_x.hist(data[data['Gender'] == gender]['RLS'], orientation='horizontal', color=color, alpha=0.5, bins=10)
    ax_hist_y.hist(data[data['Gender'] == gender]['PK'], orientation='vertical', color=color, alpha=0.5, bins=10)

# Menampilkan garis regresi
sns.regplot(x='RLS', y='PK', data=data, scatter=False, ax=ax_scatter)

# Pengaturan atribut plot
ax_hist_x.set_xticklabels([])
ax_hist_x.set_yticklabels([])
ax_hist_y.set_xticklabels([])
ax_hist_y.set_yticklabels([])

ax_hist_x.tick_params(axis='both', which='both', length=0)
ax_hist_y.tick_params(axis='both', which='both', length=0)

ax_scatter.legend(title='Gender')

plt.suptitle('Scatter Plot - Histogram RLS dan PK berdasarkan Gender')

plt.show()

"""Seperti informasi yang diperoleh pada plot sebelumnya, kali ini dapat terlihat bagaimana sebaran data berdasarkan kelompok kategorik yakni gender yang terdiri dari Laki-laki dan Perempuan. Terlihat juga garis regresi yang memperlihatkan hubungan kedua peubah, yakni pengeluaran per kapita dengan indeks pembangunan manusia.

Dari plot ini dapat terlihat secara spesifik sebaran masing-masing kategori gender. Pada histogram, terlihat bahwa sebaran nilai PK dan RLS laki-laki cenderung lebih tinggi dari perempuan.

Pada peubah RLS, nilai terkecil keseluruhan data diwakili oleh perempuan dengan nilai di sekitar angka 6, sementara tertinggi diwakili laki-laki dengan nilai di sekitar angka 12. Pada peubah PK, nilai terkecil keseluruhan data diwakili oleh perempuan dengan nilai di bawah 5000, sementara tertinggi diwakili laki-laki dengan nilai di atas 22500.

### 4) *Scatter Plot* - Histogram Rata-rata Lama Sekolah dan Pengeluaran per Kapita berdasarkan Gender (Hubungan)
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.gridspec import GridSpec

sns.set()

# Membuat figure dan grid
fig = plt.figure(figsize=(10, 7))
gs = GridSpec(4, 4, hspace=0.2)

# Subplot
ax_scatter = fig.add_subplot(gs[1:4, 0:3])
ax_hist_y = fig.add_subplot(gs[0, 0:3])
ax_hist_x = fig.add_subplot(gs[1:4, 3])

# Scatter plot
sns.scatterplot(x='RLS', y='PK', data=data, hue='Gender', ax=ax_scatter, legend=False, palette={"Laki-laki": "#66b3ff", "Perempuan": "#ff9999"})

# Histogram per kategori
colors = sns.color_palette()
for i, (gender, color) in enumerate(zip(data['Gender'].unique(), colors)):
    ax_hist_x.hist(data[data['Gender'] == gender]['PK'], orientation='horizontal', color="#66b3ff" if gender == "Laki-laki" else "#ff9999", alpha=0.5, bins=10)
    ax_hist_y.hist(data[data['Gender'] == gender]['RLS'], orientation='vertical', color="#66b3ff" if gender == "Laki-laki" else "#ff9999", alpha=0.5, bins=10)

# Garis regresi
sns.regplot(x='RLS', y='PK', data=data[data['Gender'] == 'Laki-laki'], scatter=False, color='#66b3ff', ax=ax_scatter, label='Laki-laki')
sns.regplot(x='RLS', y='PK', data=data[data['Gender'] == 'Perempuan'], scatter=False, color='#ff9999', ax=ax_scatter, label='Perempuan')

# Pengaturan atribut plot
ax_hist_x.set_xticklabels([])
ax_hist_x.set_yticklabels([])
ax_hist_y.set_xticklabels([])
ax_hist_y.set_yticklabels([])

ax_hist_x.tick_params(axis='both', which='both', length=0)
ax_hist_y.tick_params(axis='both', which='both', length=0)

ax_scatter.legend()

plt.suptitle('Scatter Plot - Histogram RLS dan PK berdasarkan Gender')

plt.show()

"""Pada plot ini ditampilkan hubungan antara Rata-rata Lama Sekolah (RLS) dan Pengeluaran per Kapita (PK) berdasarkan gender.

Sama seperti informasi yang diperoleh sebelumnya, tetapi *Scatter plot* ini dapat menunjukkan bahwa rataan nilai pengeluaran per kapita dengan interval rata-rata lama sekolah 7.5 - 11.3 lebih besar pada laki-laki daripada perempuan, ditandai dengan garis regresi laki-laki yang terletak di atas perempuan.

### 5) *Pairs Plot* Data Pengeluaran per Kapita, Indeks Pembangunan Manusia, dan Rata-rata Lama Sekolah
"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.set()

# Seleksi peubah
datanew = data[['PK', 'IPM', 'RLS', 'Gender']]

# Define fungsi histogram dan kurva density
def hist_kde(x, **kwargs):
    sns.histplot(x, kde=True, bins=10, **kwargs)

# Membuat PairGrid
plot = sns.PairGrid(datanew, hue='Gender', palette={"Laki-laki": "#66b3ff", "Perempuan": "#ff9999"})

plot.map_upper(sns.scatterplot)
plot.map_lower(sns.scatterplot)
plot.map_diag(hist_kde)

plot.add_legend()
plt.show()

"""Untuk mengeksplor sebaran dan hubungan dari setiap pasangan peubah dan kategori gender, dapat ditinjau melalui pairplot ini. Pada diagonalnya, terdapat histogram yang menampilkan sebaran data untuk masing-masing peubah dan tiap gender. Tampak pada peubah PK, laki-laki cenderung memiliki nilai yang lebih tinggi dari perempuan, sama seperti pada peubah IPM. Sementara pada peubah RLS, sebaran data laki-laki dan perempuan relatif sama, tetapi sebaran nilai laki-laki terlihat sedikit lebih tinggi dari perempuan.

Pada histogram, dapat dilihat juga letak pemusatan data pada setiap peubah, sehingga interval rataannya dapat ditaksir. Hal ini dapat dilihat lebih jelas pada garis kepekatan di setiap histogram. Pada peubah PK, data untuk perempuan memiliki kisaran rata-rata pada interval 8000 - 11000, sementara laki-laki pada interval 15000 - 18000. Pada peubah IPM, data untuk perempuan memiliki kisaran rata-rata pada interval 63 - 70, sementara laki-laki pada interval 72 - 77. Pada peubah RLS, data untuk perempuan memiliki kisaran rata-rata pada interval 6.8 - 8, sementara laki-laki pada interval 7.4 - 8.5.

Terdapat juga *scatter plot* untuk tiap kombinasi peubah yang ditampilkan pada pairplot tersebut. Dapat terlihat pada plot di atas diagonal, rataan nilai peubah y untuk laki-laki pada nilai peubah x terlihat lebih tinggi dari perempuan. Sementara itu, untuk plot-plot di bawah diagonal, rataan nilai peubah y untuk perempuan pada nilai peubah x terlihat lebih tinggi dari laki-laki. Dari seluruh *scatter plot*, terlihat bahwa ada hubungan linear positif pada seluruh kombinasi pasangan peubah.

## 6) *Heatmap* Korelasi dari Data
"""

import seaborn as sns
import matplotlib.pyplot as plt

datanum = data[['PK', 'IPM', 'RLS']]
corr_matrix = datanum.corr()

# Heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(corr_matrix, annot=True, cmap='YlGn', fmt=".2f")

plt.title('Correlation Heatmap')
plt.show()

"""Pada *heatmap* ini terlihat bagaimana ukuran korelasi dari setiap kombinasi peubah. Terlihat bahwa koefisien korelasi terkecil dimiliki oleh pasangan peubah PK dan RLS dengan nilai 0.68, sementara yang terbesar dimiliki oleh pasangan peubah PK dan IPM dengan nilai 0.93. Ukuran korelasi yang tinggi, semakin mendekati 1, menandakan bahwa kekuatan antar peubah sangat erat, dan begitu pula sebaliknya.

## 7) *Boxplot* PK, IPM, dan RLS berdasarkan Gender
"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.set()

# Seleksi peubah
datanew = data[['PK', 'IPM', 'RLS', 'Gender']]

# Define warna
colors = {"Laki-laki": "#66b3ff", "Perempuan": "#ff9999"}

# Subplot
plt.figure(figsize=(12, 8))

# Boxplot PK
plt.subplot(131)
sns.boxplot(x='Gender', y='PK', data=datanew, hue='Gender', palette=colors)
plt.title('Boxplot PK berdasarkan Gender')

# Boxplot IPM
plt.subplot(132)
sns.boxplot(x='Gender', y='IPM', data=datanew, hue='Gender', palette=colors)
plt.title('Boxplot IPM berdasarkan Gender')

# Boxplot RLS
plt.subplot(133)
sns.boxplot(x='Gender', y='RLS', data=datanew, hue='Gender', palette=colors)
plt.title('Boxplot RLS berdasarkan Gender')

plt.tight_layout()
plt.show()

"""Setelah mengetahui karakteristik antar pasangan peubah, dapat ditelusuri lebih lanjut karakteristik untuk tiap peubah pada masing-masing kategori gender. Pada peubah PK, sebaran nilai dan median laki-laki cenderung lebih tinggi dari perempuan, dan terlihat ada 3 titik pencilan di sekitar angka 22500 pada laki-laki dan 1 titik pencilan di sekitar angka 17000 pada perempuan.
Pada peubah IPM, sebaran nilai dan median laki-laki juga cenderung lebih tinggi dari perempuan dan tidak terdeteksi adanya pencilan. Pada peubah RLS, sebaran nilai dan median laki-laki juga cenderung lebih tinggi dari perempuan dan juga tidak terdeteksi adanya pencilan. Di sini terlihat juga lokasi nilai terendah pada setiap peubah untuk tiap kategori gender.

## 8) *Violin Plot* RLS, PK, dan IPM berdasarkan Gender
"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.set()

# Define warna
scatter_colors = {"Laki-laki": "#66b3ff", "Perempuan": "#fb6a4a"}

# Figure
plt.figure(figsize=(12, 6))

# Violin plot RLS
plt.subplot(1, 3, 1)
sns.violinplot(data=data, x='Gender', y='RLS', hue='Gender', palette=scatter_colors, alpha=0.5)
sns.stripplot(data=data, x='Gender', y='RLS', hue='Gender', palette=scatter_colors, alpha=0.7)
plt.title('Violin Plot RLS berdasarkan Gender')
plt.xlabel('Gender')
plt.ylabel('RLS')

# Violin plot PK
plt.subplot(1, 3, 2)
sns.violinplot(data=data, x='Gender', y='PK', hue='Gender', palette=scatter_colors, alpha=0.5)
sns.stripplot(data=data, x='Gender', y='PK', hue='Gender', palette=scatter_colors, alpha=0.7)
plt.title('Violin Plot PK berdasarkan Gender')
plt.xlabel('Gender')
plt.ylabel('PK')

# Violin plot IPM
plt.subplot(1, 3, 3)
sns.violinplot(data=data, x='Gender', y='IPM', hue='Gender', palette=scatter_colors, alpha=0.5)
sns.stripplot(data=data, x='Gender', y='IPM', hue='Gender', palette=scatter_colors, alpha=0.7)
plt.title('Violin Plot IPM berdasarkan Gender')
plt.xlabel('Gender')
plt.ylabel('IPM')

plt.tight_layout()

plt.show()

"""Untuk melihat sebaran dalam bentuk lain pada tiap peubah dan kategori gender, bisa ditinjau lagi melalui *violin plot*. Pada plot ini, ditunjukkan posisi titik-titik data dengan plot berbentuk biola dengan lebar tertentu di setiap interval yang mewakili tingkat pemusatan data.

Pada semua peubah, terlihat bahwa laki-laki memiliki sebaran nilai yang lebih tinggi dari perempuan. Pada kategori laki-laki, data cenderung terpusat pada interval 7 - 9 untuk peubah RLS, interval 13000 - 17000 untuk peubah PK, dan 70 - 80 untuk peubah IPM. Sementara pada kategori perempuan, data cenderung terpusat pada interval 6.5 - 9 untuk peubah RLS, interval 5000 - 11000 untuk peubah PK, dan 60 - 72 untuk peubah IPM.
"""